version: '3.8'

services:
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CD_PROFILE: ${CD_PROFILE}
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - auth-network
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=zabur
      - POSTGRES_DB=auth_DB
    ports:
      - "5432:5432"
    networks:
      - auth-network
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./main/resources/flyway/authorization-consent-schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./main/resources/flyway/authorization-schema.sql:/docker-entrypoint-initdb.d/2.sql
      - ./main/resources/flyway/registered-client-schema.sql:/docker-entrypoint-initdb.d/3.sql
      - ./main/resources/flyway/user-schema.sql:/docker-entrypoint-initdb.d/4.sql

networks:
  auth-network:

volumes:
  auth_data: