server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    jdbc-url: jdbc:postgresql://auth-db:5432/auth_DB
    username: postgres
    password: zabur