name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: [ "Docker Build & Push" ]
    types: [ completed ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:

      - name: Run application
        run: docker run -dp 8080:8080 --network auth-net --name auth-server andrewzaburdocker/authorization-server
