name: Checkout & Deploy to DigitalOcean

on:
  workflow_run:
    workflows: [ "Docker Build & Push" ]
    branches: [ "master" ]
    types: [ completed ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - run: | 
          CD_PROFILE=prod docker compose build
          CD_PROFILE=prod docker compose up
