name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: [ "Java CI with Maven", "Docker Build & Push" ]
    branches: [ "master" ]
    types: [ completed ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Check out code
        working-directory: .
        run: | 
          CD_PROFILE=prod docker compose build
          CD_PROFILE=prod docker compose up
