name: Deploy to DigitalOcean

on:
  workflow_run:
    workflows: [ "Docker Build & Push" ]
    branches: [ "master" ]
    types: [ completed ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2
        name: Check out code

      - name: Run application
        run: docker-compose up
