name: Docker Build & Push

on:
  workflow_run:
    workflows: [ "Java CI with Maven" ]
    branches: [ "master" ]
    types: [ completed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push Docker image
        with:
          image: andrewzaburdocker/authorization-server
          tags: v1, latest
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}